var responseCreateBiddingCategoryOk = {
    "error": null,
    "data": [
        {
            "id": 1500915220804,
            "projectId": 1493340729194,
            "createById": 1493340729194,
            "createByType": "project",
            "typeOfContractor": [
                "1.1",
                "1.1.2"
            ],
            "name": "Gói thầu thiết kế",
            "noSignName": "goi thau thiet ke",
            "createByUserId": 910200869
        },
        {
            "entityName": "role",
            "entityId": 1500915220804,
            "userId": 1493340729194,
            "userRole": "manager",
            "userCan": [
                "MANAGE_ENTITY",
                "EDIT_ENTITY",
                "VIEW_ENTITY"
            ],
            "roleFor": "biddingCategory",
            "id": 1873388219
        }
    ]
}

var responseListBiddingCategoriesOfProject = {
    "error": null,
    "data": [
        {
            "projectId": "1493340729194",
            "id": "1500914777741",
            "address": null,
            "areaOfLand": null,
            "bidCloseTime": null,
            "bidOpenTime": null,
            "bidSolicitor": null,
            "biddingForm": null,
            "categories": null,
            "city": null,
            "contructionArea": null,
            "country": null,
            "countryOfContractor": null,
            "createById": "1493340729194",
            "createByType": "project",
            "createByUserId": "910200869",
            "creditRatingOfContractor": null,
            "description": null,
            "district": null,
            "districtOfContractor": null,
            "documents": null,
            "endBuildTime": null,
            "endScheduled": null,
            "entityName": null,
            "entityStatus": null,
            "fromBudget": null,
            "investment": null,
            "listImage": null,
            "location": null,
            "materials": null,
            "minimumExperienceOfContractor": null,
            "minimumRevenueOfContractor": null,
            "name": "Gói thầu thiết kế",
            "noSignName": "goi thau thiet ke",
            "otherRequirements": null,
            "phase": null,
            "startBuildTime": null,
            "startScheduled": null,
            "timeCreate": null,
            "timeModify": null,
            "toBudget": null,
            "type": null,
            "typeOfContractor": [
                "1.1",
                "1.1.2"
            ],
            "typeOfContruction": null,
            "typeOfInvestment": null,
            "typeOfProject": null,
            "unitAreaOfLand": null,
            "unitBugget": null,
            "unitContructionArea": null,
            "unitInvestment": null,
            "unitRevenueOfContractor": null,
            "updateById": null,
            "updateByType": null,
            "updateByUserId": null
        },
        {
            "projectId": "1493340729194",
            "id": "1500914892179",
            "address": null,
            "areaOfLand": null,
            "bidCloseTime": null,
            "bidOpenTime": null,
            "bidSolicitor": null,
            "biddingForm": null,
            "categories": null,
            "city": null,
            "contructionArea": null,
            "country": null,
            "countryOfContractor": null,
            "createById": "1493340729194",
            "createByType": "project",
            "createByUserId": "910200869",
            "creditRatingOfContractor": null,
            "description": null,
            "district": null,
            "districtOfContractor": null,
            "documents": null,
            "endBuildTime": null,
            "endScheduled": null,
            "entityName": null,
            "entityStatus": null,
            "fromBudget": null,
            "investment": null,
            "listImage": null,
            "location": null,
            "materials": null,
            "minimumExperienceOfContractor": null,
            "minimumRevenueOfContractor": null,
            "name": "Gói thầu thiết kế",
            "noSignName": "goi thau thiet ke",
            "otherRequirements": null,
            "phase": null,
            "startBuildTime": null,
            "startScheduled": null,
            "timeCreate": null,
            "timeModify": null,
            "toBudget": null,
            "type": null,
            "typeOfContractor": [
                "1.1",
                "1.1.2"
            ],
            "typeOfContruction": null,
            "typeOfInvestment": null,
            "typeOfProject": null,
            "unitAreaOfLand": null,
            "unitBugget": null,
            "unitContructionArea": null,
            "unitInvestment": null,
            "unitRevenueOfContractor": null,
            "updateById": null,
            "updateByType": null,
            "updateByUserId": null
        },
        {
            "projectId": "1493340729194",
            "id": "1500915086839",
            "address": null,
            "areaOfLand": null,
            "bidCloseTime": null,
            "bidOpenTime": null,
            "bidSolicitor": null,
            "biddingForm": null,
            "categories": null,
            "city": null,
            "contructionArea": null,
            "country": null,
            "countryOfContractor": null,
            "createById": "1493340729194",
            "createByType": "project",
            "createByUserId": "910200869",
            "creditRatingOfContractor": null,
            "description": null,
            "district": null,
            "districtOfContractor": null,
            "documents": null,
            "endBuildTime": null,
            "endScheduled": null,
            "entityName": null,
            "entityStatus": null,
            "fromBudget": null,
            "investment": null,
            "listImage": null,
            "location": null,
            "materials": null,
            "minimumExperienceOfContractor": null,
            "minimumRevenueOfContractor": null,
            "name": "Gói thầu thiết kế",
            "noSignName": "goi thau thiet ke",
            "otherRequirements": null,
            "phase": null,
            "startBuildTime": null,
            "startScheduled": null,
            "timeCreate": null,
            "timeModify": null,
            "toBudget": null,
            "type": null,
            "typeOfContractor": [
                "1.1",
                "1.1.2"
            ],
            "typeOfContruction": null,
            "typeOfInvestment": null,
            "typeOfProject": null,
            "unitAreaOfLand": null,
            "unitBugget": null,
            "unitContructionArea": null,
            "unitInvestment": null,
            "unitRevenueOfContractor": null,
            "updateById": null,
            "updateByType": null,
            "updateByUserId": null
        },
        {
            "projectId": "1493340729194",
            "id": "1500915220804",
            "address": null,
            "areaOfLand": null,
            "bidCloseTime": null,
            "bidOpenTime": null,
            "bidSolicitor": null,
            "biddingForm": null,
            "categories": null,
            "city": null,
            "contructionArea": null,
            "country": null,
            "countryOfContractor": null,
            "createById": "1493340729194",
            "createByType": "project",
            "createByUserId": "910200869",
            "creditRatingOfContractor": null,
            "description": null,
            "district": null,
            "districtOfContractor": null,
            "documents": null,
            "endBuildTime": null,
            "endScheduled": null,
            "entityName": null,
            "entityStatus": null,
            "fromBudget": null,
            "investment": null,
            "listImage": null,
            "location": null,
            "materials": null,
            "minimumExperienceOfContractor": null,
            "minimumRevenueOfContractor": null,
            "name": "Gói thầu thiết kế",
            "noSignName": "goi thau thiet ke",
            "otherRequirements": null,
            "phase": null,
            "startBuildTime": null,
            "startScheduled": null,
            "timeCreate": null,
            "timeModify": null,
            "toBudget": null,
            "type": null,
            "typeOfContractor": [
                "1.1",
                "1.1.2"
            ],
            "typeOfContruction": null,
            "typeOfInvestment": null,
            "typeOfProject": null,
            "unitAreaOfLand": null,
            "unitBugget": null,
            "unitContructionArea": null,
            "unitInvestment": null,
            "unitRevenueOfContractor": null,
            "updateById": null,
            "updateByType": null,
            "updateByUserId": null
        }
    ]
}