var responseCreateContractors = {
    "error": null,
    "data": [
        {
            "id": 1500801173132,
            "entityStatus": 1,
            "numOfFollower": 0,
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "name": "Tong cong ty Vinaconex",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "address": "Phạm Hùng - Hà Nội",
            "phone": "0934523 32420",
            "email": "vi@gmail.com",
            "typeOfContractor": [
                "1.1",
                "1.2"
            ],
            "district": "Cầu Giấy",
            "origination": "Việt Nam",
            "foundedYear": 1960,
            "typeCompany": 1,
            "revenue": 123454535,
            "ownerId": 910200869,
            "createdById": 910200869,
            "userEntity": {
                "id": 910200869,
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-22T09:50:26.595Z",
                "type": null,
                "verifies": null,
                "website": null,
                "keyJWT": 1500799400945,
                "mapRoles": {
                    "910200869": {
                        "roleFor": "account",
                        "userId": "910200869",
                        "entityId": "910200869",
                        "createdById": null,
                        "entityName": "role",
                        "entityStatus": "1",
                        "id": "1105731116",
                        "modifiedById": null,
                        "parentId": null,
                        "parentType": null,
                        "timeCreate": "2017-04-27T17:27:02.313Z",
                        "timeModify": "2017-04-27T17:27:02.313Z",
                        "userCan": [
                            "EDIT_ENTITY",
                            "MANAGE_ENTITY",
                            "VIEW_ENTITY"
                        ],
                        "userRole": "owner"
                    },
                    "contractor": [],
                    "account": [
                        "910200869"
                    ],
                    "1493340729194": {
                        "roleFor": "project",
                        "userId": "910200869",
                        "entityId": "1493340729194",
                        "createdById": null,
                        "entityName": "role",
                        "entityStatus": "1",
                        "id": "-585039974",
                        "modifiedById": null,
                        "parentId": null,
                        "parentType": null,
                        "timeCreate": "2017-04-28T00:52:09.193Z",
                        "timeModify": "2017-04-28T00:52:09.193Z",
                        "userCan": [
                            "EDIT_ENTITY",
                            "MANAGE_BIDDING_CATEGORY_PROJECT",
                            "MANAGE_ENTITY",
                            "VIEW_BIDDING_CATEGORY_PROJECT",
                            "VIEW_ENTITY"
                        ],
                        "userRole": "owner"
                    },
                    "project": [
                        "1493340729194"
                    ]
                }
            },
            "noSignName": "tong cong ty vinaconex"
        },
        {
            "entityId": 1500801173132,
            "userId": 910200869,
            "userRole": "manager",
            "entityName": "role",
            "userCan": [
                "MANAGE_ENTITY",
                "EDIT_ENTITY",
                "VIEW_ENTITY",
                "RATING_OTHER_ENTITY",
                "SEND_BIDDING_CATEGORY_PROJECT",
                "EDIT_BIDDING_CATEGORY_PROJECT",
                "VIEW_BIDDING_CATEGORY_PROJECT"
            ],
            "roleFor": "role",
            "id": -300338983
        }
    ]
}

var responseUpdateContractor =  {
    "error": null,
    "data": {
        "info": {
            "queriedHost": "172.104.49.141:9042",
            "triedHosts": {},
            "achievedConsistency": 10
        },
        "columns": null,
        "pageState": null
    }
}

var responseDetailContractor = {
    "error": null,
    "data": [
        {
            "id": "1500801173132",
            "address": "Phạm Hùng - Hà Nội",
            "city": "Hà Nội",
            "contacts": null,
            "country": "Việt Nam",
            "createdById": "910200869",
            "description": null,
            "district": "Cầu Giấy",
            "documents": null,
            "email": "vi@gmail.com",
            "entityName": null,
            "entityStatus": "1",
            "fax": null,
            "finances": null,
            "foundedYear": 1960,
            "houselinkranking": null,
            "isHouseLinkMember": null,
            "isVerifiedicense": null,
            "language": null,
            "location": null,
            "logo": null,
            "mainMarkets": null,
            "modifiedById": "910200869",
            "name": "Tong cong ty Vinaconex updated",
            "noSignName": "tong cong ty vinaconex",
            "numOfEmployees": null,
            "numOfExpProject": null,
            "numOfFollower": "0",
            "numOfRating": "0",
            "numOfRating1Star": "0",
            "numOfRating2Star": "0",
            "numOfRating3Star": "0",
            "numOfRating4Star": "0",
            "numOfRating5Star": "0",
            "numOfView": "0",
            "origination": "Việt Nam",
            "ownerId": "910200869",
            "parentId": null,
            "parentType": null,
            "phone": "0934523 32420",
            "price": null,
            "qualityManagement": null,
            "revenue": "123454535",
            "subBusiness": null,
            "taxCode": null,
            "timeCreate": null,
            "timeModify": null,
            "totalRanking": null,
            "type": null,
            "typeCompany": 1,
            "typeOfBusiness": null,
            "typeOfCompany": null,
            "typeOfConstruction": null,
            "typeOfContractor": [
                "1.1",
                "1.2"
            ],
            "typeOfProject": null,
            "unitPrice": "VND",
            "unitRevenue": "VND",
            "userEntity": {
                "id": 910200869,
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-22T09:50:26.595Z",
                "type": null,
                "verifies": null,
                "website": null,
                "keyJWT": 1500799400945,
                "mapRoles": {
                    "910200869": {
                        "roleFor": "account",
                        "userId": "910200869",
                        "entityId": "910200869",
                        "createdById": null,
                        "entityName": "role",
                        "entityStatus": "1",
                        "id": "1105731116",
                        "modifiedById": null,
                        "parentId": null,
                        "parentType": null,
                        "timeCreate": "2017-04-27T17:27:02.313Z",
                        "timeModify": "2017-04-27T17:27:02.313Z",
                        "userCan": [
                            "EDIT_ENTITY",
                            "MANAGE_ENTITY",
                            "VIEW_ENTITY"
                        ],
                        "userRole": "owner"
                    },
                    "contractor": [],
                    "account": [
                        "910200869"
                    ],
                    "1493340729194": {
                        "roleFor": "project",
                        "userId": "910200869",
                        "entityId": "1493340729194",
                        "createdById": null,
                        "entityName": "role",
                        "entityStatus": "1",
                        "id": "-585039974",
                        "modifiedById": null,
                        "parentId": null,
                        "parentType": null,
                        "timeCreate": "2017-04-28T00:52:09.193Z",
                        "timeModify": "2017-04-28T00:52:09.193Z",
                        "userCan": [
                            "EDIT_ENTITY",
                            "MANAGE_BIDDING_CATEGORY_PROJECT",
                            "MANAGE_ENTITY",
                            "VIEW_BIDDING_CATEGORY_PROJECT",
                            "VIEW_ENTITY"
                        ],
                        "userRole": "owner"
                    },
                    "project": [
                        "1493340729194"
                    ]
                }
            },
            "wallImage": null,
            "website": null,
            "myRating": null,
            "ratingCandidates": []
        },
        {
            "roleFor": "role",
            "userId": "910200869",
            "entityId": "1500801173132",
            "createdById": null,
            "entityName": "role",
            "entityStatus": null,
            "id": "-300338983",
            "modifiedById": null,
            "parentId": null,
            "parentType": null,
            "timeCreate": null,
            "timeModify": null,
            "userCan": [
                "EDIT_BIDDING_CATEGORY_PROJECT",
                "EDIT_ENTITY",
                "MANAGE_ENTITY",
                "RATING_OTHER_ENTITY",
                "SEND_BIDDING_CATEGORY_PROJECT",
                "VIEW_BIDDING_CATEGORY_PROJECT",
                "VIEW_ENTITY"
            ],
            "userRole": "manager"
        }
    ]
}

var responseSearchContractor = {
    "error": null,
    "data": [
        {
            "id": 1500801173132,
            "entityStatus": 1,
            "numOfFollower": 0,
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "name": "Tong cong ty Vinaconex updated",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "address": "Phạm Hùng - Hà Nội",
            "phone": "0934523 32420",
            "email": "vi@gmail.com",
            "typeOfContractor": [
                "1.1",
                "1.2"
            ],
            "district": "Cầu Giấy",
            "origination": "Việt Nam",
            "foundedYear": 1960,
            "typeCompany": 1,
            "revenue": 123454535,
            "ownerId": 910200869,
            "createdById": 910200869,
            "userEntity": "{\"id\":910200869,\"accountStatus\":null,\"accountType\":null,\"address\":null,\"avatar\":null,\"city\":\"TP Hồ Chí Minh\",\"country\":\"Việt Nam\",\"createdById\":null,\"district\":null,\"email\":\"trinhvietnambk@gmail.com\",\"emailNotifies\":null,\"entityName\":\"account\",\"entityStatus\":\"1\",\"fax\":null,\"isValidatePhone\":null,\"isWaitingResetPassword\":null,\"language\":null,\"lastName\":null,\"location\":null,\"modifiedById\":\"910200869\",\"name\":\"Trịnh Viết Nam\",\"numOfFollower\":null,\"numOfFollowing\":\"2\",\"numOfRating\":null,\"numOfRating1Star\":null,\"numOfRating2Star\":null,\"numOfRating3Star\":null,\"numOfRating4Star\":null,\"numOfRating5Star\":null,\"numOfView\":null,\"parentId\":null,\"parentType\":null,\"paymentMethods\":null,\"phone\":null,\"suggestEmail\":\"trinhvietnambk\",\"taxCode\":null,\"tempPassword\":null,\"timeCreate\":\"2017-04-27T17:27:02.330Z\",\"timeModify\":\"2017-07-22T09:50:26.595Z\",\"type\":null,\"verifies\":null,\"website\":null,\"keyJWT\":1500799400945,\"mapRoles\":{\"910200869\":{\"roleFor\":\"account\",\"userId\":\"910200869\",\"entityId\":\"910200869\",\"createdById\":null,\"entityName\":\"role\",\"entityStatus\":\"1\",\"id\":\"1105731116\",\"modifiedById\":null,\"parentId\":null,\"parentType\":null,\"timeCreate\":\"2017-04-27T17:27:02.313Z\",\"timeModify\":\"2017-04-27T17:27:02.313Z\",\"userCan\":[\"EDIT_ENTITY\",\"MANAGE_ENTITY\",\"VIEW_ENTITY\"],\"userRole\":\"owner\"},\"contractor\":[],\"account\":[\"910200869\"],\"1493340729194\":{\"roleFor\":\"project\",\"userId\":\"910200869\",\"entityId\":\"1493340729194\",\"createdById\":null,\"entityName\":\"role\",\"entityStatus\":\"1\",\"id\":\"-585039974\",\"modifiedById\":null,\"parentId\":null,\"parentType\":null,\"timeCreate\":\"2017-04-28T00:52:09.193Z\",\"timeModify\":\"2017-04-28T00:52:09.193Z\",\"userCan\":[\"EDIT_ENTITY\",\"MANAGE_BIDDING_CATEGORY_PROJECT\",\"MANAGE_ENTITY\",\"VIEW_BIDDING_CATEGORY_PROJECT\",\"VIEW_ENTITY\"],\"userRole\":\"owner\"},\"project\":[\"1493340729194\"]}}",
            "noSignName": "tong cong ty vinaconex",
            "modifiedById": 910200869,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Vinaconex Hà Nội",
            "address": "Phạm Hùng",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Tổng công ty xây dựng Việt nam",
            "foundedYear": 1980,
            "typeCompany": 2,
            "revenue": 1200000000,
            "ownerId": "910200869",
            "timeCreate": 1499005541625,
            "timeModify": 1499005541625,
            "createdById": "910200869",
            "id": 1499005541626,
            "noSignName": "vinaconex ha noi",
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Công ty xây dựng HouseLink",
            "address": "Duy Tân",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Công ty hàng đầu trong ngahfnh xâu dựng",
            "foundedYear": 2010,
            "typeCompany": 1,
            "revenue": 12000000,
            "ownerId": "910200869",
            "timeCreate": 1498983474693,
            "timeModify": 1498983474693,
            "createdById": "910200869",
            "id": 1498983474695,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "id": 1497602111843,
            "entityStatus": 1,
            "timeCreate": "2017-06-16T08:35:11.874Z",
            "timeModify": "2017-06-16T08:36:22.799Z",
            "entityName": "contractor",
            "numOfFollower": "1",
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "typeCompany": 1,
            "email": "user1@example.com",
            "name": "Học Viên Ngân Hàng",
            "address": "12 Chùa Bộc, Quang Trung",
            "phone": "012-345-6789",
            "country": "Việt Nam",
            "city": "Hà Nội",
            "district": "Hai Bà Trưng",
            "foundedYear": 1961,
            "typeOfContractor": [
                "1.1.1",
                "1.1.2",
                "1.1.3",
                "1.1.4",
                "1.1.5",
                "1.1.6",
                "1.1.10",
                "1.2.2",
                "1.2.6",
                "1.3.4",
                "1.3.7",
                "1.3.8",
                "1.3.9"
            ],
            "qualityManagement": 2,
            "origination": "v, i",
            "language": "en",
            "finances": [
                {
                    "year": 2016,
                    "revenue": 211000000000,
                    "totalAsset": 333000000000,
                    "totalLiabilitie": 4223000000000,
                    "charterCapital": 1223000000000,
                    "currencyUnit": "VND"
                },
                {
                    "year": 2017,
                    "revenue": 233000000000,
                    "totalAsset": 2434000000000,
                    "totalLiabilitie": 24432000000000,
                    "charterCapital": 344000000000,
                    "currencyUnit": "VND"
                }
            ],
            "revenue": 233000000000,
            "ownerId": "-502127578",
            "createdById": null,
            "userEntity": "{\"id\":\"-502127578\",\"accountStatus\":null,\"accountType\":null,\"address\":null,\"avatar\":null,\"city\":\"Hà Nội\",\"country\":\"Việt Nam\",\"createdById\":null,\"district\":null,\"email\":\"user1@example.com\",\"emailNotifies\":null,\"entityName\":\"account\",\"entityStatus\":\"1\",\"fax\":null,\"isValidatePhone\":null,\"isWaitingResetPassword\":null,\"keyJWT\":\"1497597156621\",\"language\":null,\"lastName\":null,\"location\":null,\"modifiedById\":\"-502127578\",\"name\":\"Personal No 1\",\"numOfFollower\":null,\"numOfFollowing\":null,\"numOfRating\":null,\"numOfRating1Star\":null,\"numOfRating2Star\":null,\"numOfRating3Star\":null,\"numOfRating4Star\":null,\"numOfRating5Star\":null,\"numOfView\":null,\"parentId\":null,\"parentType\":null,\"password\":\"123123\",\"paymentMethods\":null,\"phone\":\"123\",\"suggestEmail\":\"user1\",\"taxCode\":null,\"tempPassword\":null,\"timeCreate\":\"2017-04-26T07:32:52.426Z\",\"timeModify\":\"2017-06-16T07:12:36.621Z\",\"type\":null,\"verifies\":null,\"website\":null,\"mapRoles\":{\"-502127578\":{\"roleFor\":\"account\",\"userId\":\"-502127578\",\"entityId\":\"-502127578\",\"createdById\":null,\"entityName\":\"role\",\"entityStatus\":\"1\",\"id\":\"1704883097\",\"modifiedById\":null,\"parentId\":null,\"parentType\":null,\"timeCreate\":\"2017-04-26T07:32:52.420Z\",\"timeModify\":\"2017-04-26T07:32:52.420Z\",\"userCan\":[\"EDIT_ENTITY\",\"MANAGE_ENTITY\",\"VIEW_ENTITY\"],\"userRole\":\"owner\"},\"account\":[\"-502127578\"],\"contractor\":[],\"project\":[]}}",
            "noSignName": "hoc vien ngan hang",
            "modifiedById": "-502127578",
            "logo": "http://hvnh.edu.vn/upload/2306/20130506/logo-hvnh.png",
            "description": "       Dự án lớn",
            "typeOfProject": [
                4,
                6,
                8,
                9
            ],
            "typeOfConstruction": [
                1
            ],
            "typeOfCompany": 1,
            "FOLLOWING": true,
            "owner": {
                "id": "-502127578",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "Hà Nội",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "user1@example.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1497597156621",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "-502127578",
                "name": "Personal No 1",
                "numOfFollower": null,
                "numOfFollowing": null,
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": "123",
                "suggestEmail": "user1",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-26T07:32:52.426Z",
                "timeModify": "2017-06-16T07:12:36.621Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "id": 1496039001170,
            "entityStatus": 1,
            "timeCreate": "2017-05-29T06:23:21.205Z",
            "timeModify": "2017-06-08T08:56:01.089Z",
            "entityName": "contractor",
            "numOfFollower": "1",
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "typeCompany": 1,
            "email": "thanhlong.houselink@gmail.com",
            "name": "Hoabinh Corp",
            "address": "Quận 3, HCM",
            "phone": "1235-433-3333",
            "fax": "1234-456-7755",
            "country": "Việt Nam",
            "city": "TP Hồ Chí Minh",
            "district": "Quận 3",
            "website": "hbcr.vn",
            "foundedYear": 1989,
            "description": "Leading company in construction",
            "typeOfContractor": [
                "1",
                "3",
                "4"
            ],
            "qualityManagement": 1,
            "origination": "vi",
            "language": "vi",
            "revenue": 42,
            "ownerId": "1501928694",
            "createdById": null,
            "noSignName": "hoabinh corp",
            "modifiedById": "1501928694",
            "logo": "http://houselink.com.vn/website/image/ir.attachment/365_579ad4d/datas",
            "FOLLOWING": true,
            "owner": {
                "id": "1501928694",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "Hà Nội",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "thanhlong.houselink@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1499786681569",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "1501928694",
                "name": "ABC com",
                "numOfFollower": null,
                "numOfFollowing": "11",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123456",
                "paymentMethods": null,
                "phone": "123456789",
                "suggestEmail": "thanhlong.houselink",
                "taxCode": "123456",
                "tempPassword": null,
                "timeCreate": "2017-04-27T01:52:18.206Z",
                "timeModify": "2017-07-11T15:24:41.569Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "id": 1495960782837,
            "entityStatus": 1,
            "timeCreate": "2017-05-28T08:39:43.004Z",
            "timeModify": "2017-06-05T15:21:37.488Z",
            "entityName": "contractor",
            "numOfFollower": "3",
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "typeCompany": 1,
            "email": "nguyenthanhlong@gmail.com",
            "name": "Contractor 3",
            "address": "Tang 13 Keangnam Hanoi Landmark Tower, Me Tri",
            "phone": "0123456789",
            "fax": "0123456789",
            "country": "Việt Nam",
            "city": "Khánh Hòa",
            "district": "Diên Khánh",
            "website": "www.example.com",
            "foundedYear": 2009,
            "description": "This is about",
            "typeOfContractor": [
                "2",
                "3",
                "5"
            ],
            "qualityManagement": 1,
            "origination": "Viet Nam",
            "language": "en",
            "revenue": 42,
            "ownerId": -1559187261,
            "createdById": null,
            "userEntity": "{\"id\":-1559187261,\"accountStatus\":null,\"accountType\":null,\"address\":null,\"avatar\":null,\"city\":\"Ha Noi\",\"country\":\"Vietnam\",\"createdById\":null,\"district\":null,\"email\":\"phuonglh0420@gmail.com\",\"emailNotifies\":null,\"entityName\":\"account\",\"entityStatus\":\"1\",\"fax\":null,\"isValidatePhone\":null,\"isWaitingResetPassword\":null,\"language\":null,\"lastName\":null,\"location\":null,\"modifiedById\":\"-1559187261\",\"name\":\"Phuong Le Hoai\",\"numOfFollower\":null,\"numOfFollowing\":\"10\",\"numOfRating\":null,\"numOfRating1Star\":null,\"numOfRating2Star\":null,\"numOfRating3Star\":null,\"numOfRating4Star\":null,\"numOfRating5Star\":null,\"numOfView\":null,\"parentId\":null,\"parentType\":null,\"paymentMethods\":null,\"phone\":null,\"suggestEmail\":\"phuonglh0420\",\"taxCode\":null,\"tempPassword\":null,\"timeCreate\":\"2017-04-25T16:59:25.743Z\",\"timeModify\":\"2017-05-28T01:45:52.451Z\",\"type\":null,\"verifies\":null,\"website\":null,\"keyJWT\":1495959439680}",
            "noSignName": "contractor 3",
            "modifiedById": "-1559187261",
            "logo": "http://www.theworldfolio.com/img_db/timthumb.php?src=img_db/articles/article-588b754b7d016.jpg&w=800&z=1",
            "FOLLOWING": true,
            "owner": {
                "id": "-1559187261",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "Ha Noi",
                "country": "Vietnam",
                "createdById": null,
                "district": null,
                "email": "phuonglh0420@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1498191381529",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "-1559187261",
                "name": "Phuong Le Hoai",
                "numOfFollower": null,
                "numOfFollowing": "4",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "phuonglh0420",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-25T16:59:25.743Z",
                "timeModify": "2017-06-23T04:16:21.530Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "id": 1495959446241,
            "entityStatus": 1,
            "timeCreate": "2017-05-28T08:17:26.427Z",
            "timeModify": "2017-06-05T02:30:12.632Z",
            "entityName": "contractor",
            "numOfFollower": "1",
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "typeCompany": 1,
            "email": "nguyenthanhlong@gmail.com",
            "name": "Contractor 3",
            "address": "Tang 13 Keangnam Hanoi Landmark Tower, Me Tri",
            "phone": "0123456789",
            "fax": "0123456789",
            "country": "Việt Nam",
            "city": "Khánh Hòa",
            "district": "Diên Khánh",
            "website": "www.example.com",
            "foundedYear": 2009,
            "description": "This is aboutnnn",
            "typeOfContractor": [
                "2",
                "3",
                "5"
            ],
            "qualityManagement": 1,
            "origination": "Viet Nam",
            "language": "en",
            "revenue": 42,
            "ownerId": -1559187261,
            "createdById": null,
            "userEntity": "{\"id\":-1559187261,\"accountStatus\":null,\"accountType\":null,\"address\":null,\"avatar\":null,\"city\":\"Ha Noi\",\"country\":\"Vietnam\",\"createdById\":null,\"district\":null,\"email\":\"phuonglh0420@gmail.com\",\"emailNotifies\":null,\"entityName\":\"account\",\"entityStatus\":\"1\",\"fax\":null,\"isValidatePhone\":null,\"isWaitingResetPassword\":null,\"language\":null,\"lastName\":null,\"location\":null,\"modifiedById\":\"-1559187261\",\"name\":\"Phuong Le Hoai\",\"numOfFollower\":null,\"numOfFollowing\":\"10\",\"numOfRating\":null,\"numOfRating1Star\":null,\"numOfRating2Star\":null,\"numOfRating3Star\":null,\"numOfRating4Star\":null,\"numOfRating5Star\":null,\"numOfView\":null,\"parentId\":null,\"parentType\":null,\"paymentMethods\":null,\"phone\":null,\"suggestEmail\":\"phuonglh0420\",\"taxCode\":null,\"tempPassword\":null,\"timeCreate\":\"2017-04-25T16:59:25.743Z\",\"timeModify\":\"2017-05-28T01:45:52.451Z\",\"type\":null,\"verifies\":null,\"website\":null,\"keyJWT\":1495959439680}",
            "noSignName": "contractor 3",
            "modifiedById": "-1559187261",
            "FOLLOWING": true,
            "owner": {
                "id": "-1559187261",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "Ha Noi",
                "country": "Vietnam",
                "createdById": null,
                "district": null,
                "email": "phuonglh0420@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1498191381529",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "-1559187261",
                "name": "Phuong Le Hoai",
                "numOfFollower": null,
                "numOfFollowing": "4",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "phuonglh0420",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-25T16:59:25.743Z",
                "timeModify": "2017-06-23T04:16:21.530Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "id": 1495645711504,
            "entityStatus": 1,
            "timeCreate": "2017-05-24T17:08:31.625Z",
            "timeModify": "2017-05-25T01:39:57.592Z",
            "entityName": "contractor",
            "numOfFollower": "-1",
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "typeCompany": 1,
            "email": "phuonglh0420@gmail.com",
            "name": "BCI Asia Edited",
            "address": "#801, Tòa nhà 18/11 Thái Hà ",
            "phone": "0443-537-8548",
            "fax": "0443-537-8549",
            "country": "Việt Nam",
            "city": "Hà Nội",
            "district": "Đống Đa",
            "foundedYear": 2007,
            "description": "BCI Asia là một đơn vị kết hợp chặt chẽ với hiệp hội kiến trúc sư Á Châu và hoạt động uy tín khắp trong thị trường xây dựng Á Châu nói chung và Việt Nam nói riêng. Chúng tôi xin tự tóm lược một số nét phác thảo từ hoạt động của chính mình. BCI Asia là đơn vị báo cáo chuyên nghiệp khối lượng lớn các dự án đang và sẽ được xúc tiến trong lĩnh vực xây dựng, đem lại hàng loạt các cơ hội kinh tế cho các đại diện cung cấp sản phẩm và các công trình vừa và lớn. Về cơ bản, BCI Asia chuyên nghiệp cung cấp: •\tPhương tiện đến với một mạng lưới rộng lớn các đối tác kinh tế. •\tLàm tăng cơ hội ký hợp đồng trong các dự án cho chính các đơn vị thành viên. • Độc quyền về thông tin, được báo cáo từ một đội ngũ chuyên nghiệp. •\tPhương tiện đến với một nguồn thông tin đem lại lợi nhuận cao giúp đội ngũ các công ty thành viên tiết kiệm thời gian tìm kiếm dự án để tập trung vào kinh doanh. •\tĐem đến cơ hội tìm kiếm dự án trực tuyến nhanh nhất và quản lý hành chính cho phòng kinh doanh một cách hiệu quả. •\tHỗ trợ các thành viên bằng mạng lưới tìm kiếm thông tin dự án nóng. •\tCập nhật các thông tin xây dựng và hỗ trợ các tài liệu huấn luyện tiếp cận công trình. •\tChất lượng nguồn thông tin được đảm bảo tuyệt đối. BCI Asia phục vụ chuyên nghiệp trong ngành xây dựng toàn thế giới với hệ thống báo cáo và tìm kiếm dự án tương lai tại các quốc gia Đông Nam Á thông qua hệ thống thông tin dự án trực tuyến. Thông tin của BCI Asia được báo cáo theo 7 giai đoạn từ: giai đoạn ý tưởng của chủ đầu tư, đến giai đoạn thiết kế, kéo dài sang giai đoạn chọn thầu, giai đoạn khởi công xây dựng…BCI Asia sẽ cung cấp cho doanh nghiệp một hệ thống thông tin trực tuyến (real-time online data) về những dự án đang diễn ra ở Việt Nam cùng những thông tin liên hệ của tất cả các đơn vị cơ vai trò trong dự án (Chủ đầu tư, đơn vị kiến trúc, nhà thầu… của các công trình) và được cập nhật theo tiến độ của dự án.\n",
            "typeOfProject": [
                1,
                2,
                3
            ],
            "typeOfContractor": [
                "4",
                "6"
            ],
            "qualityManagement": 1,
            "origination": "vi",
            "language": "vi",
            "revenue": 42,
            "ownerId": "-1559187261",
            "createdById": null,
            "noSignName": "bci asia edited",
            "modifiedById": "-1559187261",
            "finances": [
                {
                    "totalAsset": 0,
                    "revenue": 10,
                    "year": 2014,
                    "totalLiabilitie": 0,
                    "charterCapital": 0,
                    "currencyUnit": "VND"
                },
                {
                    "totalAsset": 0,
                    "revenue": 2,
                    "year": 2015,
                    "totalLiabilitie": 0,
                    "charterCapital": 0,
                    "currencyUnit": "VND"
                },
                {
                    "totalAsset": 0,
                    "revenue": 32,
                    "year": 2016,
                    "totalLiabilitie": 0,
                    "charterCapital": 0,
                    "currencyUnit": "VND"
                }
            ],
            "FOLLOWING": true,
            "owner": {
                "id": "-1559187261",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "Ha Noi",
                "country": "Vietnam",
                "createdById": null,
                "district": null,
                "email": "phuonglh0420@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1498191381529",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "-1559187261",
                "name": "Phuong Le Hoai",
                "numOfFollower": null,
                "numOfFollowing": "4",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "phuonglh0420",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-25T16:59:25.743Z",
                "timeModify": "2017-06-23T04:16:21.530Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "id": 1495645407375,
            "entityStatus": 1,
            "timeCreate": "2017-05-24T17:03:27.464Z",
            "timeModify": "2017-06-02T04:04:53.048Z",
            "entityName": "contractor",
            "numOfFollower": "1",
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "typeCompany": 1,
            "email": "phuonglh0420@gmail.com",
            "name": "Nihon Sekkei Vietnam",
            "address": "9th Floor., Grand Building, No.30-32 Hoa Ma Street",
            "phone": "8443-976-5770",
            "fax": "043-976-5772",
            "country": "Việt Nam",
            "city": "Hà Nội",
            "district": "Hai Bà Trưng",
            "website": "http://www.nihonsekkei.co.jp/en/",
            "foundedYear": 1967,
            "description": "   Nihon Sekkei là một công ty Nhật Bản có hơn 40 năm kinh nghiệm trong lĩnh vực xây dựng. Cụ thể, hoạt động chính của công ty liên quan đến phát triển đô thị, môi trường, thiết kế kiến trúc và đánh giá. Công nghệ tối tân cùng kinh nghiệm tích lũy từ ngày đầu thành lập đã giúp công ty đáp ứng nhu cầu khách hàng. Là công ty liên kết với Nihon Sekkei, đặt cơ sở tại Hà Nội, Nihon Sekkei Việt Nam cũng chuyên về kiến trúc, xây dựng. Tại Việt Nam, danh tiếng Nihon Sekkei cũng được biết đến rộng rãi qua các dự án nổi bật như bệnh viện trung ương Huế, bệnh viện Bạch Mai, trụ sở Agribank, trường đại học FPT…",
            "typeOfProject": [
                1,
                2,
                3
            ],
            "typeOfContractor": [
                "1.1.5",
                "1.1.8",
                "1.1.9",
                "1.1.12",
                "1.2.2",
                "1.2.5",
                "1.3.9"
            ],
            "qualityManagement": 1,
            "origination": "vi",
            "language": "vi",
            "revenue": 42,
            "ownerId": "-1559187261",
            "createdById": null,
            "noSignName": "nihon sekkei vietnam",
            "modifiedById": "-1559187261",
            "finances": [
                {
                    "totalAsset": 0,
                    "revenue": 1,
                    "year": 2014,
                    "totalLiabilitie": 0,
                    "charterCapital": 0,
                    "currencyUnit": "VND"
                },
                {
                    "totalAsset": 0,
                    "revenue": 2,
                    "year": 2015,
                    "totalLiabilitie": 0,
                    "charterCapital": 0,
                    "currencyUnit": "VND"
                },
                {
                    "totalAsset": 0,
                    "revenue": 3,
                    "year": 2016,
                    "totalLiabilitie": 0,
                    "charterCapital": 0,
                    "currencyUnit": "VND"
                }
            ],
            "logo": "https://nzcontractors.co.nz/uploads/sites/nzcontractors/theme/images/site_banner.jpg",
            "typeOfCompany": 1,
            "FOLLOWING": true,
            "owner": {
                "id": "-1559187261",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "Ha Noi",
                "country": "Vietnam",
                "createdById": null,
                "district": null,
                "email": "phuonglh0420@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1498191381529",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "-1559187261",
                "name": "Phuong Le Hoai",
                "numOfFollower": null,
                "numOfFollowing": "4",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "phuonglh0420",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-25T16:59:25.743Z",
                "timeModify": "2017-06-23T04:16:21.530Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "id": 1495645138763,
            "entityStatus": 1,
            "timeCreate": "2017-05-24T16:58:58.822Z",
            "timeModify": "2017-05-24T16:58:58.763Z",
            "entityName": "contractor",
            "numOfFollower": "1",
            "numOfView": 0,
            "numOfRating": 0,
            "numOfRating1Star": 0,
            "numOfRating2Star": 0,
            "numOfRating3Star": 0,
            "numOfRating4Star": 0,
            "numOfRating5Star": 0,
            "unitRevenue": "VND",
            "unitPrice": "VND",
            "typeCompany": 1,
            "email": "phuonglh0420@gmail.com",
            "name": "Vinata International joint venture",
            "address": "Đường Khuất Duy Tiến",
            "phone": "045-533-8401232",
            "fax": "045-533-788",
            "country": "Việt Nam",
            "city": "Hà Nội",
            "district": "Cầu Giấy",
            "website": "http://www.vinata.com.vn/",
            "foundedYear": 1993,
            "description": "      Đi vào hoạt động năm 1993, công ty TNHH quốc tế liên doanh Vinata là sự kết hợp giữa Vinaconex và tập đoàn Taisei Nhật Bản, chuyên về xây dựng, quản lý dự án và thiết kế nội thất cho những văn phòng đại diện của các công ty nước ngoài ở Việt Nam. 10 năm hoạt động kinh doanh, nhờ vào sự ứng dụng công nghệ và đội ngũ nhân viên giàu kinh nghiệm, Vinata tự hào khi đã tiếp quản nhiều dự án quan trọng cho các khách hàng Nhật như Toyota, Sapporo Office, Sumidenso, Tokyo Micro…",
            "typeOfProject": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "typeOfContractor": [
                "1",
                "2",
                "3",
                "4"
            ],
            "qualityManagement": 1,
            "origination": "vi",
            "language": "vi",
            "revenue": 42,
            "ownerId": "-1559187261",
            "createdById": null,
            "noSignName": "vinata international joint venture",
            "logo": "http://www.vinaconex.com.vn/images/thum_big.jpg",
            "typeOfConstruction": [
                1,
                2,
                3
            ],
            "typeOfCompany": 1,
            "FOLLOWING": true,
            "owner": {
                "id": "-1559187261",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "Ha Noi",
                "country": "Vietnam",
                "createdById": null,
                "district": null,
                "email": "phuonglh0420@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1498191381529",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "-1559187261",
                "name": "Phuong Le Hoai",
                "numOfFollower": null,
                "numOfFollowing": "4",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "phuonglh0420",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-25T16:59:25.743Z",
                "timeModify": "2017-06-23T04:16:21.530Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        }
    ]
}