var responseCreateProject= {
    "error": null,
    "data": [
        {
            "id": "1493340729194",
            "address": "Số 4 - Ngõ 191 -Phố Khương Thượng",
            "areaOfLand": null,
            "bidCloseTime": "2017-05-06T00:00:00.000Z",
            "bidOpenTime": "2017-04-28T00:00:00.000Z",
            "bidSolicitor": [
                "123456789"
            ],
            "biddingForm": 1,
            "categories": null,
            "city": "Bà Rịa-Vũng Tàu",
            "contructionArea": null,
            "country": "Việt Nam",
            "countryOfContractor": "Việt Nam",
            "createdById": "910200869",
            "creditRatingOfContractor": 4,
            "description": null,
            "district": "Châu Đức",
            "districtOfContractor": "Bà Rịa-Vũng Tàu",
            "documents": [
                {
                    "name": "Tài liệu kết cấu",
                    "fileId": "2332",
                    "timeCreate": "02/05/2017 23:10",
                    "type": null,
                    "url": "https://houselink.com.vn/files/2332"
                },
                {
                    "name": "Tài liệu thiết kế",
                    "fileId": "1232",
                    "timeCreate": "02/05/2017 23:04",
                    "type": null,
                    "url": "https://houselink.com.vn/files/1232"
                }
            ],
            "endBudget": "33252",
            "endBuildTime": "2017-06-30T00:00:00.000Z",
            "endScheduled": "2017-06-03T00:00:00.000Z",
            "entityName": "project",
            "entityStatus": "1",
            "fromBudget": "3",
            "investment": null,
            "isReadyForBidding": true,
            "listImage": null,
            "listVideo": null,
            "location": {
                "lat": 21.0309471,
                "lon": 105.781722
            },
            "materials": null,
            "minimumExperienceOfContractor": 5,
            "minimumRevenueOfContractor": "10000",
            "modifiedById": "910200869",
            "name": "Project edited",
            "noSignName": "xay dung nha rieng ",
            "numOfBids": null,
            "numOfFollower": "2",
            "numOfRating": "0",
            "numOfRating1Star": "0",
            "numOfRating2Star": "0",
            "numOfRating3Star": "0",
            "numOfRating4Star": "0",
            "numOfRating5Star": "0",
            "numOfView": "0",
            "otherRequirements": null,
            "ownerId": "910200869",
            "parentId": null,
            "parentType": null,
            "phase": 1,
            "startBuildTime": "2017-04-29T00:00:00.000Z",
            "startScheduled": "2017-05-03T00:00:00.000Z",
            "timeCreate": "2017-04-28T00:52:09.201Z",
            "timeModify": "2017-05-24T16:55:45.769Z",
            "type": null,
            "typeOfConstruction": null,
            "typeOfContractor": [
                "1"
            ],
            "typeOfContruction": 2,
            "typeOfInvestment": 1,
            "typeOfProject": 2,
            "unitAreaOfLand": null,
            "unitBugget": "VND",
            "unitContructionArea": null,
            "unitInvestment": null,
            "unitRevenueOfContractor": "VND",
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500716940575",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-22T09:50:26.595Z",
                "type": null,
                "verifies": null,
                "website": null
            },
            "FOLLOWING": true
        },
        {
            "roleFor": "project",
            "userId": "910200869",
            "entityId": "1493340729194",
            "createdById": null,
            "entityName": "role",
            "entityStatus": "1",
            "id": "-585039974",
            "modifiedById": null,
            "parentId": null,
            "parentType": null,
            "timeCreate": "2017-04-28T00:52:09.193Z",
            "timeModify": "2017-04-28T00:52:09.193Z",
            "userCan": [
                "EDIT_ENTITY",
                "MANAGE_BIDDING_CATEGORY_PROJECT",
                "MANAGE_ENTITY",
                "VIEW_BIDDING_CATEGORY_PROJECT",
                "VIEW_ENTITY"
            ],
            "userRole": "owner"
        }
    ]
}

var responseUpdateProjectOk = {
    "error": null,
    "data": {
        "info": {
            "queriedHost": "172.104.49.141:9042",
            "triedHosts": {},
            "achievedConsistency": 10
        },
        "columns": null,
        "pageState": null
    }
}

var responseDetailProjectNoRole = {
    "error": null,
    "data": [
        {
            "id": "1493340729194",
            "address": "Số 4 - Ngõ 191 -Phố Khương Thượng",
            "areaOfLand": null,
            "bidCloseTime": "2017-05-06T00:00:00.000Z",
            "bidOpenTime": "2017-04-28T00:00:00.000Z",
            "bidSolicitor": [
                "123456789"
            ],
            "biddingForm": 1,
            "categories": null,
            "city": "Bà Rịa-Vũng Tàu",
            "contructionArea": null,
            "country": "Việt Nam",
            "countryOfContractor": "Việt Nam",
            "createdById": "910200869",
            "creditRatingOfContractor": 4,
            "description": null,
            "district": "Châu Đức",
            "districtOfContractor": "Bà Rịa-Vũng Tàu",
            "documents": [
                {
                    "name": "Tài liệu kết cấu",
                    "fileId": "2332",
                    "timeCreate": "02/05/2017 23:10",
                    "type": null,
                    "url": "https://houselink.com.vn/files/2332"
                },
                {
                    "name": "Tài liệu thiết kế",
                    "fileId": "1232",
                    "timeCreate": "02/05/2017 23:04",
                    "type": null,
                    "url": "https://houselink.com.vn/files/1232"
                }
            ],
            "endBudget": "33252",
            "endBuildTime": "2017-06-30T00:00:00.000Z",
            "endScheduled": "2017-06-03T00:00:00.000Z",
            "entityName": "project",
            "entityStatus": "1",
            "fromBudget": "3",
            "investment": null,
            "isReadyForBidding": true,
            "listImage": null,
            "listVideo": null,
            "location": {
                "lat": 21.0309471,
                "lon": 105.781722
            },
            "materials": null,
            "minimumExperienceOfContractor": 5,
            "minimumRevenueOfContractor": "10000",
            "modifiedById": "910200869",
            "name": "Project edited 1",
            "noSignName": "xay dung nha rieng ",
            "numOfBids": null,
            "numOfFollower": "2",
            "numOfRating": "0",
            "numOfRating1Star": "0",
            "numOfRating2Star": "0",
            "numOfRating3Star": "0",
            "numOfRating4Star": "0",
            "numOfRating5Star": "0",
            "numOfView": "0",
            "otherRequirements": null,
            "ownerId": "910200869",
            "parentId": null,
            "parentType": null,
            "phase": 1,
            "startBuildTime": "2017-04-29T00:00:00.000Z",
            "startScheduled": "2017-05-03T00:00:00.000Z",
            "timeCreate": "2017-04-28T00:52:09.201Z",
            "timeModify": "2017-05-24T16:55:45.769Z",
            "type": null,
            "typeOfConstruction": null,
            "typeOfContractor": [
                "1"
            ],
            "typeOfContruction": 2,
            "typeOfInvestment": 1,
            "typeOfProject": 2,
            "unitAreaOfLand": null,
            "unitBugget": "VND",
            "unitContructionArea": null,
            "unitInvestment": null,
            "unitRevenueOfContractor": "VND",
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500716940575",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-22T09:50:26.595Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        null
    ]
}
var responseDetailProjectHasRole = {
    "error": null,
    "data": [
        {
            "id": "1493340729194",
            "address": "Số 4 - Ngõ 191 -Phố Khương Thượng",
            "areaOfLand": null,
            "bidCloseTime": "2017-05-06T00:00:00.000Z",
            "bidOpenTime": "2017-04-28T00:00:00.000Z",
            "bidSolicitor": [
                "123456789"
            ],
            "biddingForm": 1,
            "categories": null,
            "city": "Bà Rịa-Vũng Tàu",
            "contructionArea": null,
            "country": "Việt Nam",
            "countryOfContractor": "Việt Nam",
            "createdById": "910200869",
            "creditRatingOfContractor": 4,
            "description": null,
            "district": "Châu Đức",
            "districtOfContractor": "Bà Rịa-Vũng Tàu",
            "documents": [
                {
                    "name": "Tài liệu kết cấu",
                    "fileId": "2332",
                    "timeCreate": "02/05/2017 23:10",
                    "type": null,
                    "url": "https://houselink.com.vn/files/2332"
                },
                {
                    "name": "Tài liệu thiết kế",
                    "fileId": "1232",
                    "timeCreate": "02/05/2017 23:04",
                    "type": null,
                    "url": "https://houselink.com.vn/files/1232"
                }
            ],
            "endBudget": "33252",
            "endBuildTime": "2017-06-30T00:00:00.000Z",
            "endScheduled": "2017-06-03T00:00:00.000Z",
            "entityName": "project",
            "entityStatus": "1",
            "fromBudget": "3",
            "investment": null,
            "isReadyForBidding": true,
            "listImage": null,
            "listVideo": null,
            "location": {
                "lat": 21.0309471,
                "lon": 105.781722
            },
            "materials": null,
            "minimumExperienceOfContractor": 5,
            "minimumRevenueOfContractor": "10000",
            "modifiedById": "910200869",
            "name": "Project edited 1",
            "noSignName": "xay dung nha rieng ",
            "numOfBids": null,
            "numOfFollower": "2",
            "numOfRating": "0",
            "numOfRating1Star": "0",
            "numOfRating2Star": "0",
            "numOfRating3Star": "0",
            "numOfRating4Star": "0",
            "numOfRating5Star": "0",
            "numOfView": "0",
            "otherRequirements": null,
            "ownerId": "910200869",
            "parentId": null,
            "parentType": null,
            "phase": 1,
            "startBuildTime": "2017-04-29T00:00:00.000Z",
            "startScheduled": "2017-05-03T00:00:00.000Z",
            "timeCreate": "2017-04-28T00:52:09.201Z",
            "timeModify": "2017-05-24T16:55:45.769Z",
            "type": null,
            "typeOfConstruction": null,
            "typeOfContractor": [
                "1"
            ],
            "typeOfContruction": 2,
            "typeOfInvestment": 1,
            "typeOfProject": 2,
            "unitAreaOfLand": null,
            "unitBugget": "VND",
            "unitContructionArea": null,
            "unitInvestment": null,
            "unitRevenueOfContractor": "VND",
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            },
            "FOLLOWING": true
        },
        {
            "roleFor": "project",
            "userId": "910200869",
            "entityId": "1493340729194",
            "createdById": null,
            "entityName": "role",
            "entityStatus": "1",
            "id": "-585039974",
            "modifiedById": null,
            "parentId": null,
            "parentType": null,
            "timeCreate": "2017-04-28T00:52:09.193Z",
            "timeModify": "2017-04-28T00:52:09.193Z",
            "userCan": [
                "EDIT_ENTITY",
                "MANAGE_BIDDING_CATEGORY_PROJECT",
                "MANAGE_ENTITY",
                "VIEW_BIDDING_CATEGORY_PROJECT",
                "VIEW_ENTITY"
            ],
            "userRole": "owner"
        }
    ]
}

var responseSearchProject = {
    "error": null,
    "data": [
        {
            "name": "Đường trên cao Hà Đông 6",
            "address": "Nguyễn Trãi",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Đường cho tầu cao tốc",
            "phase": 1,
            "startBuildTime": 1451779200000,
            "endBuildTime": 1488931200000,
            "fromBudget": 11000000,
            "endBudget": 15000000,
            "ownerId": "910200869",
            "timeCreate": 1498706276711,
            "timeModify": 1498706276711,
            "createdById": "910200869",
            "id": 1498706276711,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Đường trên cao Hà Đông 6",
            "address": "Nguyễn Trãi",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Đường cho tầu cao tốc",
            "phase": 1,
            "startBuildTime": 1451779200000,
            "endBuildTime": 1488931200000,
            "fromBudget": 11000000,
            "endBudget": 15000000,
            "ownerId": "910200869",
            "timeCreate": 1498705955497,
            "timeModify": 1498705955497,
            "createdById": "910200869",
            "id": 1498705955497,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Dự án công nghệ 12345",
            "address": "Cầu Giấy",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Công nghệ cao",
            "phase": 1,
            "startBuildTime": 1483315200000,
            "endBuildTime": 1491350400000,
            "fromBudget": 1111111,
            "endBudget": 2000000,
            "ownerId": "910200869",
            "timeCreate": 1498697814577,
            "timeModify": 1498697814577,
            "createdById": "910200869",
            "id": 1498697814577,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Dự án Hạ tầng 445566",
            "address": "Nam Từ Liêm",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Đường cho tầu cao tốc",
            "phase": 1,
            "startBuildTime": 1451779200000,
            "endBuildTime": 1488931200000,
            "fromBudget": 11000000,
            "endBudget": 15000000,
            "ownerId": "910200869",
            "timeCreate": 1498697814563,
            "timeModify": 1498697814563,
            "createdById": "910200869",
            "id": 1498697814563,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Dự án công nghệ Cầu Giấy",
            "address": "Cầu Giấy",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Công nghệ cao",
            "phase": 1,
            "startBuildTime": 1483315200000,
            "endBuildTime": 1491350400000,
            "fromBudget": 1111111,
            "endBudget": 2000000,
            "ownerId": "910200869",
            "timeCreate": 1498697692258,
            "timeModify": 1498697692258,
            "createdById": "910200869",
            "id": 1498697692258,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Dự án Hạ tầng Nam Hà Nội",
            "address": "Nam Từ Liêm",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Đường cho tầu cao tốc",
            "phase": 1,
            "startBuildTime": 1451779200000,
            "endBuildTime": 1488931200000,
            "fromBudget": 11000000,
            "endBudget": 15000000,
            "ownerId": "910200869",
            "timeCreate": 1498697692249,
            "timeModify": 1498697692249,
            "createdById": "910200869",
            "id": 1498697692249,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Dự án Đường cao tốc Nhổn - Ga Hà Nội",
            "address": "Ba Đình - Nam Từ Liêm - Hà Nội",
            "city": "Hà Nôi",
            "country": "Việt Nam",
            "description": "Đương cáo tốc trên cao",
            "phase": 2,
            "startBuildTime": 1486080000000,
            "endBuildTime": 1496534400000,
            "fromBudget": 30000,
            "endBudget": 50000,
            "ownerId": "910200869",
            "timeCreate": 1498697547218,
            "timeModify": 1498697547218,
            "createdById": "910200869",
            "id": 1498697547218,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Dự án công nghệ Cầu Giấy",
            "address": "Cầu Giấy",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Công nghệ cao",
            "phase": 1,
            "startBuildTime": 1483315200000,
            "endBuildTime": 1491350400000,
            "fromBudget": 1111111,
            "endBudget": 2000000,
            "ownerId": "910200869",
            "timeCreate": 1498697547208,
            "timeModify": 1498697547208,
            "createdById": "910200869",
            "id": 1498697547208,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Dự án Hạ tầng Nam Hà Nội",
            "address": "Nam Từ Liêm",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Đường cho tầu cao tốc",
            "phase": 1,
            "startBuildTime": 1451779200000,
            "endBuildTime": 1488931200000,
            "fromBudget": 11000000,
            "endBudget": 15000000,
            "ownerId": "910200869",
            "timeCreate": 1498697547198,
            "timeModify": 1498697547198,
            "createdById": "910200869",
            "id": 1498697547198,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        },
        {
            "name": "Đường trên cao Hà Đông 6",
            "address": "Nguyễn Trãi",
            "city": "Hà Nội",
            "country": "Việt Nam",
            "description": "Đường cho tầu cao tốc",
            "phase": 1,
            "startBuildTime": 1451779200000,
            "endBuildTime": 1488931200000,
            "fromBudget": 11000000,
            "endBudget": 15000000,
            "ownerId": "910200869",
            "timeCreate": 1498694847469,
            "timeModify": 1498694847469,
            "createdById": "910200869",
            "id": 1498694847470,
            "owner": {
                "id": "910200869",
                "accountStatus": null,
                "accountType": null,
                "address": null,
                "avatar": null,
                "city": "TP Hồ Chí Minh",
                "country": "Việt Nam",
                "createdById": null,
                "district": null,
                "email": "trinhvietnambk@gmail.com",
                "emailNotifies": null,
                "entityName": "account",
                "entityStatus": "1",
                "fax": null,
                "isValidatePhone": null,
                "isWaitingResetPassword": null,
                "keyJWT": "1500799400945",
                "language": null,
                "lastName": null,
                "location": null,
                "modifiedById": "910200869",
                "name": "Trịnh Viết Nam",
                "numOfFollower": null,
                "numOfFollowing": "2",
                "numOfRating": null,
                "numOfRating1Star": null,
                "numOfRating2Star": null,
                "numOfRating3Star": null,
                "numOfRating4Star": null,
                "numOfRating5Star": null,
                "numOfView": null,
                "parentId": null,
                "parentType": null,
                "password": "123123",
                "paymentMethods": null,
                "phone": null,
                "suggestEmail": "trinhvietnambk",
                "taxCode": null,
                "tempPassword": null,
                "timeCreate": "2017-04-27T17:27:02.330Z",
                "timeModify": "2017-07-23T08:43:20.945Z",
                "type": null,
                "verifies": null,
                "website": null
            }
        }
    ]
}